---
title: "STA380 Project Proposal"
subtitle: "Bootstrap Estimation of Healthcare Data"
author: "Group 11"
date: "2026-02-10"
output:
  pdf_document:
    latex_engine: xelatex
fontsize: 11pt
geometry: margin=1in
bibliography: bibliography.bib
header-includes:
  - \usepackage{xcolor}
---

# 1. Project Topic

Bootstrap Estimation of Sleep Duration Differences by Depression Status

# 2. Simulation vs. Dataset

The project will use a healthcare dataset.

# 3. Project Details

We will use bootstrap resampling method to estimate the sampling distribution of sleep duration statistics in a healthcare dataset.

The study will focus on comparing sleep duration between individuals with depression and those without depression. We will apply bootstrap resampling with replacement within each group seperately to estimate uncertainty in summary statistics[@marqueze2015natural].

The following outputs will be provided:

- Boostrap sampling distribution of mean sleep duration
- Boostrap sampling distribution of median sleep duration
- Bootstrap confidence intervals for both mean and median
- Reference lines for both mean and median
- Visualizations of bootstrap distribution using histograms

# 4. User Inputs (Shiny Components)

Users will be able to modify the following:

1. Setting the seed.
2. Select the data presented: 
- Mean sleep duration
- Median sleep duration
- Summary statistic of bootstrap estimates
- Bootstrap confidence interval
- Visualizing the distribution with histogram
3. Modify the Confidence Interval with different confidence level.(e.g. 90%, 95%, 99%.)
4. Customizing the plot such as the color.
5. Download the plot if required. 

# Generative AI Use
This proposal did not use generative AI tools.

# References
\nocite{*}


